<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://mdw.qwest.com/listener/webservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://mdw.qwest.com/listener/webservice" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types xmlns:soap12enc="http://www.w3.org/2003/05/soap-encoding" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsr="http://www.openuri.org/2002/10/soap/reliability/" xmlns:conv="http://www.openuri.org/2002/04/wsdl/conversation/">
    <s:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mdw.qwest.com/listener/webservice">
      <s:import schemaLocation="soapEncodi_1.xsd" namespace="http://schemas.xmlsoap.org/soap/encoding/" />
    </s:schema>
  </wsdl:types>
  <wsdl:message name="invokeWebService">
    <wsdl:part xmlns:partns="http://www.w3.org/2001/XMLSchema" name="ServiceName" type="partns:string" />
    <wsdl:part xmlns:partns="http://www.w3.org/2001/XMLSchema" name="RequestDetails" type="partns:string" />
  </wsdl:message>
  <wsdl:message name="invokeWebServiceResponse">
    <wsdl:part xmlns:partns="http://www.w3.org/2001/XMLSchema" name="Response" type="partns:string" />
  </wsdl:message>
  <wsdl:portType name="MDWWebServicePort">
    <wsdl:operation name="invokeWebService">
      <wsdl:input message="tns:invokeWebService" />
      <wsdl:output message="tns:invokeWebServiceResponse" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MDWWebServicePort" type="tns:MDWWebServicePort">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc" />
    <wsdl:operation name="invokeWebService">
      <soap:operation soapAction="" style="rpc" />
      <wsdl:input>
        <soap:body use="encoded" namespace="http://mdw.qwest.com/listener/webservice" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="encoded" namespace="http://mdw.qwest.com/listener/webservice" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MDWWebService">
    <wsdl:port name="MDWWebServicePort" binding="tns:MDWWebServicePort">
      <soap:address location="http://ecomt200.dev.qintra.com:7622/FulfillmentWFMDWWeb/MDWWebService" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>