//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Script
{
    using System;
    using System.Xml;
    using System.Xml.Schema;
    using System.Collections.Generic;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.CheckpointFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Ext.CheckpointLogicOperators;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Ext.CheckpointRules;
    using HP.ST.Ext.CheckpointRules.ArrayCheckpoints;
    
    
    public partial class WorkFlowScript
    {
        
        private void set_StServiceCallActivity4_checkpoints(STActivityBase activity)
        {
            VTDPropertyInfoBase stracturalOutputEnvelope = new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)=\'Envelope\'][1]");
            IList<VTDPropertyInfoBase> stracturalPropsInfo = new List<VTDPropertyInfoBase>();
            CpValObj ExpectedSchema = new CpValObj("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<xs:schema xmlns:tns=\"http://schemas.xml" +
                    "soap.org/soap/envelope/\" targetNamespace=\"http://schemas.xmlsoap.org/soap/envelo" +
                    "pe/\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n  <xs:element name=\"Envelope\"" +
                    " type=\"tns:Envelope\" />\r\n  <xs:complexType name=\"Envelope\">\r\n    <xs:sequence>\r\n" +
                    "      <xs:element minOccurs=\"0\" ref=\"tns:Header\" />\r\n      <xs:element minOccurs" +
                    "=\"1\" ref=\"tns:Body\" />\r\n      <xs:any minOccurs=\"0\" maxOccurs=\"unbounded\" proces" +
                    "sContents=\"lax\" />\r\n    </xs:sequence>\r\n    <xs:anyAttribute processContents=\"la" +
                    "x\" />\r\n  </xs:complexType>\r\n  <xs:element name=\"Header\" type=\"tns:Header\" />\r\n  " +
                    "<xs:complexType name=\"Header\">\r\n    <xs:sequence>\r\n      <xs:any minOccurs=\"0\" m" +
                    "axOccurs=\"unbounded\" processContents=\"lax\" />\r\n    </xs:sequence>\r\n    <xs:anyAt" +
                    "tribute processContents=\"lax\" />\r\n  </xs:complexType>\r\n  <xs:element name=\"Body\"" +
                    " type=\"tns:Body\" />\r\n  <xs:complexType name=\"Body\">\r\n    <xs:sequence>\r\n      <x" +
                    "s:any minOccurs=\"0\" maxOccurs=\"unbounded\" namespace=\"##any\" processContents=\"lax" +
                    "\" />\r\n    </xs:sequence>\r\n    <xs:anyAttribute namespace=\"##any\" processContents" +
                    "=\"lax\">\r\n      <xs:annotation>\r\n        <xs:documentation>Prose in the spec does" +
                    " not specify that attributes are allowed on the Body element</xs:documentation>\r" +
                    "\n      </xs:annotation>\r\n    </xs:anyAttribute>\r\n  </xs:complexType>\r\n  <xs:attr" +
                    "ibute name=\"mustUnderstand\">\r\n    <xs:simpleType>\r\n      <xs:restriction base=\"x" +
                    "s:boolean\">\r\n        <xs:pattern value=\"0|1\" />\r\n      </xs:restriction>\r\n    </" +
                    "xs:simpleType>\r\n  </xs:attribute>\r\n  <xs:attribute name=\"actor\" type=\"xs:anyURI\"" +
                    " />\r\n  <xs:simpleType name=\"encodingStyle\">\r\n    <xs:annotation>\r\n      <xs:docu" +
                    "mentation>\'encodingStyle\' indicates any canonicalization conventions followed in" +
                    " the contents of the containing element.  For example, the value \'http://schemas" +
                    ".xmlsoap.org/soap/encoding/\' indicates the pattern described in SOAP specificati" +
                    "on</xs:documentation>\r\n    </xs:annotation>\r\n    <xs:list itemType=\"xs:anyURI\" /" +
                    ">\r\n  </xs:simpleType>\r\n  <xs:attribute name=\"encodingStyle\" type=\"tns:encodingSt" +
                    "yle\" />\r\n  <xs:attributeGroup name=\"encodingStyle\">\r\n    <xs:attribute ref=\"tns:" +
                    "encodingStyle\" />\r\n  </xs:attributeGroup>\r\n  <xs:element name=\"Fault\" type=\"tns:" +
                    "Fault\" />\r\n  <xs:complexType name=\"Fault\" final=\"extension\">\r\n    <xs:annotation" +
                    ">\r\n      <xs:documentation>Fault reporting structure</xs:documentation>\r\n    </x" +
                    "s:annotation>\r\n    <xs:sequence>\r\n      <xs:element name=\"faultcode\" type=\"xs:QN" +
                    "ame\" />\r\n      <xs:element name=\"faultstring\" type=\"xs:string\" />\r\n      <xs:ele" +
                    "ment minOccurs=\"0\" name=\"faultactor\" type=\"xs:anyURI\" />\r\n      <xs:element minO" +
                    "ccurs=\"0\" name=\"detail\" type=\"tns:detail\" />\r\n    </xs:sequence>\r\n  </xs:complex" +
                    "Type>\r\n  <xs:complexType name=\"detail\">\r\n    <xs:sequence>\r\n      <xs:any minOcc" +
                    "urs=\"0\" maxOccurs=\"unbounded\" namespace=\"##any\" processContents=\"lax\" />\r\n    </" +
                    "xs:sequence>\r\n    <xs:anyAttribute namespace=\"##any\" processContents=\"lax\" />\r\n " +
                    " </xs:complexType>\r\n</xs:schema>", XmlTypeCode.None);
            stracturalPropsInfo.Add(stracturalOutputEnvelope);
            BaseCPRule StracturalRule = new StracturalRule(activity, ExpectedSchema, stracturalPropsInfo);
            activity.AddCheckpointRule(StracturalRule);

        }
    }
}
